function CodeDefine() { 
this.def = new Array();
this.def["IsrOverrun"] = {file: "ert_main_c.html",line:23,type:"var"};
this.def["isRateRunning"] = {file: "ert_main_c.html",line:24,type:"var"};
this.def["need2runFlags"] = {file: "ert_main_c.html",line:26,type:"var"};
this.def["rt_OneStep"] = {file: "ert_main_c.html",line:28,type:"fcn"};
this.def["stopRequested"] = {file: "ert_main_c.html",line:90,type:"var"};
this.def["main"] = {file: "ert_main_c.html",line:91,type:"fcn"};
this.def["sinPWM_3f_mukdik_B"] = {file: "sinPWM_3f_mukdik_c.html",line:24,type:"var"};
this.def["sinPWM_3f_mukdik_DW"] = {file: "sinPWM_3f_mukdik_c.html",line:27,type:"var"};
this.def["sinPWM_3f_mukdik_M_"] = {file: "sinPWM_3f_mukdik_c.html",line:30,type:"var"};
this.def["sinPWM_3f_mukdik_M"] = {file: "sinPWM_3f_mukdik_c.html",line:31,type:"var"};
this.def["plook_u32u32u64n32_evenc_f"] = {file: "sinPWM_3f_mukdik_c.html",line:33,type:"fcn"};
this.def["intrp1d_s32s64s64u32u64n32l_f"] = {file: "sinPWM_3f_mukdik_c.html",line:64,type:"fcn"};
this.def["plook_u32u16u64n48_evenc_f"] = {file: "sinPWM_3f_mukdik_c.html",line:77,type:"fcn"};
this.def["intrp1d_s16s32s32u32u64n48l_f"] = {file: "sinPWM_3f_mukdik_c.html",line:111,type:"fcn"};
this.def["sinPWM_3f_mukdik_SetEventsForThisBaseStep"] = {file: "sinPWM_3f_mukdik_c.html",line:130,type:"fcn"};
this.def["rate_monotonic_scheduler"] = {file: "sinPWM_3f_mukdik_c.html",line:144,type:"fcn"};
this.def["sinPWM_3f_mukdik_step0"] = {file: "sinPWM_3f_mukdik_c.html",line:157,type:"fcn"};
this.def["sinPWM_3f_mukdik_step1"] = {file: "sinPWM_3f_mukdik_c.html",line:389,type:"fcn"};
this.def["sinPWM_3f_mukdik_initialize"] = {file: "sinPWM_3f_mukdik_c.html",line:403,type:"fcn"};
this.def["sinPWM_3f_mukdik_terminate"] = {file: "sinPWM_3f_mukdik_c.html",line:968,type:"fcn"};
this.def["B_sinPWM_3f_mukdik_T"] = {file: "sinPWM_3f_mukdik_h.html",line:63,type:"type"};
this.def["DW_sinPWM_3f_mukdik_T"] = {file: "sinPWM_3f_mukdik_h.html",line:68,type:"type"};
this.def["Restart_Value"] = {file: "sinPWM_3f_mukdik_h.html",line:72,type:"var"};
this.def["P_sinPWM_3f_mukdik_T"] = {file: "sinPWM_3f_mukdik_types_h.html",line:32,type:"type"};
this.def["RT_MODEL_sinPWM_3f_mukdik_T"] = {file: "sinPWM_3f_mukdik_types_h.html",line:35,type:"type"};
this.def["sinPWM_3f_mukdik_P"] = {file: "sinPWM_3f_mukdik_data_c.html",line:24,type:"var"};
this.def["rtGetInf"] = {file: "rtGetInf_c.html",line:31,type:"fcn"};
this.def["rtGetInfF"] = {file: "rtGetInf_c.html",line:55,type:"fcn"};
this.def["rtGetMinusInf"] = {file: "rtGetInf_c.html",line:66,type:"fcn"};
this.def["rtGetMinusInfF"] = {file: "rtGetInf_c.html",line:90,type:"fcn"};
this.def["rtGetNaN"] = {file: "rtGetNaN_c.html",line:31,type:"fcn"};
this.def["rtGetNaNF"] = {file: "rtGetNaN_c.html",line:55,type:"fcn"};
this.def["rtInf"] = {file: "rt_nonfinite_c.html",line:29,type:"var"};
this.def["rtMinusInf"] = {file: "rt_nonfinite_c.html",line:30,type:"var"};
this.def["rtNaN"] = {file: "rt_nonfinite_c.html",line:31,type:"var"};
this.def["rtInfF"] = {file: "rt_nonfinite_c.html",line:32,type:"var"};
this.def["rtMinusInfF"] = {file: "rt_nonfinite_c.html",line:33,type:"var"};
this.def["rtNaNF"] = {file: "rt_nonfinite_c.html",line:34,type:"var"};
this.def["rt_InitInfAndNaN"] = {file: "rt_nonfinite_c.html",line:40,type:"fcn"};
this.def["rtIsInf"] = {file: "rt_nonfinite_c.html",line:52,type:"fcn"};
this.def["rtIsInfF"] = {file: "rt_nonfinite_c.html",line:58,type:"fcn"};
this.def["rtIsNaN"] = {file: "rt_nonfinite_c.html",line:64,type:"fcn"};
this.def["rtIsNaNF"] = {file: "rt_nonfinite_c.html",line:70,type:"fcn"};
this.def["BigEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:41,type:"type"};
this.def["LittleEndianIEEEDouble"] = {file: "rt_nonfinite_h.html",line:48,type:"type"};
this.def["IEEESingle"] = {file: "rt_nonfinite_h.html",line:55,type:"type"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:59,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["int64_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["uint64_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:74,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:75,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:76,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:77,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:78,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:79,type:"type"};
this.def["ulonglong_T"] = {file: "rtwtypes_h.html",line:80,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:81,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:82,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:83,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:93,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:98,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:103,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:110,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:117,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:124,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:131,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:138,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:145,type:"type"};
this.def["cint64_T"] = {file: "rtwtypes_h.html",line:152,type:"type"};
this.def["cuint64_T"] = {file: "rtwtypes_h.html",line:159,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:180,type:"type"};
this.def["config_ADC_SOC0"] = {file: "MW_c28xx_adc_c.html",line:8,type:"fcn"};
this.def["init_board"] = {file: "MW_c28xx_board_c.html",line:8,type:"fcn"};
this.def["disableWatchdog"] = {file: "MW_c28xx_csl_c.html",line:9,type:"fcn"};
this.def["enable_interrupts"] = {file: "MW_c28xx_csl_c.html",line:17,type:"fcn"};
this.def["enableExtInterrupt"] = {file: "MW_c28xx_csl_c.html",line:24,type:"fcn"};
this.def["config_ePWM_GPIO"] = {file: "MW_c28xx_pwm_c.html",line:8,type:"fcn"};
this.def["getLoopbackIP"] = {file: "MW_target_hardware_resources_h.html",line:15,type:"var"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_c.html"] = "../ert_main.c";
	this.html2Root["ert_main_c.html"] = "ert_main_c.html";
	this.html2SrcPath["sinPWM_3f_mukdik_c.html"] = "../sinPWM_3f_mukdik.c";
	this.html2Root["sinPWM_3f_mukdik_c.html"] = "sinPWM_3f_mukdik_c.html";
	this.html2SrcPath["sinPWM_3f_mukdik_h.html"] = "../sinPWM_3f_mukdik.h";
	this.html2Root["sinPWM_3f_mukdik_h.html"] = "sinPWM_3f_mukdik_h.html";
	this.html2SrcPath["sinPWM_3f_mukdik_private_h.html"] = "../sinPWM_3f_mukdik_private.h";
	this.html2Root["sinPWM_3f_mukdik_private_h.html"] = "sinPWM_3f_mukdik_private_h.html";
	this.html2SrcPath["sinPWM_3f_mukdik_types_h.html"] = "../sinPWM_3f_mukdik_types.h";
	this.html2Root["sinPWM_3f_mukdik_types_h.html"] = "sinPWM_3f_mukdik_types_h.html";
	this.html2SrcPath["sinPWM_3f_mukdik_data_c.html"] = "../sinPWM_3f_mukdik_data.c";
	this.html2Root["sinPWM_3f_mukdik_data_c.html"] = "sinPWM_3f_mukdik_data_c.html";
	this.html2SrcPath["rtGetInf_c.html"] = "../rtGetInf.c";
	this.html2Root["rtGetInf_c.html"] = "rtGetInf_c.html";
	this.html2SrcPath["rtGetInf_h.html"] = "../rtGetInf.h";
	this.html2Root["rtGetInf_h.html"] = "rtGetInf_h.html";
	this.html2SrcPath["rtGetNaN_c.html"] = "../rtGetNaN.c";
	this.html2Root["rtGetNaN_c.html"] = "rtGetNaN_c.html";
	this.html2SrcPath["rtGetNaN_h.html"] = "../rtGetNaN.h";
	this.html2Root["rtGetNaN_h.html"] = "rtGetNaN_h.html";
	this.html2SrcPath["rt_nonfinite_c.html"] = "../rt_nonfinite.c";
	this.html2Root["rt_nonfinite_c.html"] = "rt_nonfinite_c.html";
	this.html2SrcPath["rt_nonfinite_h.html"] = "../rt_nonfinite.h";
	this.html2Root["rt_nonfinite_h.html"] = "rt_nonfinite_h.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_c28xx_adc_c.html"] = "../MW_c28xx_adc.c";
	this.html2Root["MW_c28xx_adc_c.html"] = "MW_c28xx_adc_c.html";
	this.html2SrcPath["MW_c28xx_board_c.html"] = "../MW_c28xx_board.c";
	this.html2Root["MW_c28xx_board_c.html"] = "MW_c28xx_board_c.html";
	this.html2SrcPath["MW_c28xx_csl_c.html"] = "../MW_c28xx_csl.c";
	this.html2Root["MW_c28xx_csl_c.html"] = "MW_c28xx_csl_c.html";
	this.html2SrcPath["MW_c28xx_pie_h.html"] = "../MW_c28xx_pie.h";
	this.html2Root["MW_c28xx_pie_h.html"] = "MW_c28xx_pie_h.html";
	this.html2SrcPath["MW_c28xx_pwm_c.html"] = "../MW_c28xx_pwm.c";
	this.html2Root["MW_c28xx_pwm_c.html"] = "MW_c28xx_pwm_c.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_c.html","sinPWM_3f_mukdik_c.html","sinPWM_3f_mukdik_h.html","sinPWM_3f_mukdik_private_h.html","sinPWM_3f_mukdik_types_h.html","sinPWM_3f_mukdik_data_c.html","rtGetInf_c.html","rtGetInf_h.html","rtGetNaN_c.html","rtGetNaN_h.html","rt_nonfinite_c.html","rt_nonfinite_h.html","rtwtypes_h.html","rtmodel_h.html","MW_c28xx_adc_c.html","MW_c28xx_board_c.html","MW_c28xx_csl_c.html","MW_c28xx_pie_h.html","MW_c28xx_pwm_c.html","MW_target_hardware_resources_h.html"];
